---
- name: The Great One - Automated Fortress Build
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Facts
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/facts.yaml"
      
    - name: Initiation
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/initiation.yaml"

    - name: Kernel Hardening
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/99-fortress.conf
        reload: yes
      loop:
        - { name: 'net.ipv4.ip_forward', value: '1' }
        - { name: 'net.ipv6.conf.all.forwarding', value: '1' }
        - { name: 'net.ipv4.icmp_echo_ignore_all', value: '1' }
        - { name: 'net.ipv6.icmp.echo_ignore_all', value: '1' }
        - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
        - { name: 'net.ipv6.conf.all.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.all.rp_filter', value: '1' }
        - { name: 'net.ipv4.conf.default.rp_filter', value: '1' }

    - name: NetworkManager
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/network-manager.yaml"  

    - name: FirewallD
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/firewalld.yaml"  
    
    - name: Dnscrypt-Proxy
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/dnscrypt-proxy.yaml"
      
    - name: Pi-Hole
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/pihole.yaml"

    - name: systemd-resolved
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/systemd-resolved.yaml"

    - name: Tailscale
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/tailscale.yaml"  

    - name: Minimal GUI Stack
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/gui-stack.yaml"

    - name: Misc
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/misc.yaml"
  
  handlers:
    - name: Reload SystemD
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Reload FirewallD
      ansible.builtin.command: firewall-cmd --reload

    - name: Restart Pi-hole
      ansible.builtin.service:
        name: pihole-FTL
        state: restarted

    - name: Reboot Required
      ansible.builtin.set_fact:
        needs_reboot: true
        
    - name: Restart journald
      ansible.builtin.service:
        name: systemd-journald
        state: restarted
