- name: gui-stack - Install
  ansible.builtin.apt:
    name:
      - xrdp
      - xorgxrdp
      - openbox
      - tint2
      - xterm
      - rpi-chromium-mods
    state: present

- name: gui-stack - Configure XRDP to start Openbox
  ansible.builtin.copy:
    dest: /home/fortress/.xsession
    content: |
      exec openbox-session
    owner: fortress
    group: fortress
    mode: '0644'

- name: gui-stack - Ensure Service is running
  ansible.builtin.service:
    name: xrdp
    state: started
    enabled: yes

- name: gui-stack - Create Openbox config directory
  ansible.builtin.file:
    path: /home/fortress/.config/openbox
    state: directory
    owner: fortress
    group: fortress

- name: gui-stack - Configure Openbox Autostart (Launch tint2)
  ansible.builtin.copy:
    dest: /home/fortress/.config/openbox/autostart
    content: |
      tint2 &
    owner: fortress
    group: fortress
    mode: '0755'
