- name: gui-stack - Install
  ansible.builtin.apt:
    name:
      - xrdp
      - xorgxrdp
      - openbox
      - tint2
      - xterm
      - rpi-chromium-mods
    state: present

- name: gui-stack - Configure XRDP to start Openbox
  ansible.builtin.copy:
    dest: /home/fortress/.xsession
    owner: fortress
    group: fortress
    mode: '0644'
    content: "exec openbox-session"

- name: gui-stack - Ensure Service is running
  ansible.builtin.service:
    name: gui-stack - xrdp
    state: started
    enabled: yes

- name: gui-stack - Create Openbox config directory
  ansible.builtin.file:
    path: /home/fortress/.config/openbox
    state: directory
    owner: fortress
    group: fortress

- name: gui-stack - Configure Openbox Autostart (Launch tint2)
  ansible.builtin.template:
    src: "{{ playbook_dir }}/files/openbox-autostart"
    dest: /home/fortress/.config/openbox/autostart
    owner: fortress
    group: fortress
    mode: '0755'
