---
- name: Gui-stack - Install
  ansible.builtin.package:
    name:
      - xrdp
      - xorgxrdp
      - icewm
      - xterm
      - "{{ 'rpi-chromium-mods' if (ansible_distribution == 'Debian' and is_pi | bool) else 'chromium' }}"
    state: present

- name: Gui-stack - Configure XRDP to start IceWM
  ansible.builtin.copy:
    dest: /home/fortress/.xsession
    content: |
      #! /bin/bash

      exec /usr/bin/icewm-session
    owner: fortress
    group: fortress
    mode: "0755"

- name: Gui-stack - Ensure Service is running
  ansible.builtin.service:
    name: xrdp
    state: started
    enabled: true
