- name: network-manager - Deploy Config for Global Stealth Configuration
  ansible.builtin.template:
    src: "{{ playbook_dir }}/files/99-fortress-stealth.conf"
    dest: /etc/NetworkManager/conf.d/99-fortress-stealth.conf
    owner: root
    group: root
    mode: '0644'

- name: network-manager - Deploy Config for wlan0
  ansible.builtin.template:
    src: "{{ playbook_dir }}/files/Fortress-AP.j2"
    dest: /etc/NetworkManager/system-connections/Fortress-AP.nmconnection
    owner: root
    group: root
    mode: '0600'
  register: nm_config_file

- name: network-manager - Deploy Config for eth0
  ansible.builtin.template:
    src: "{{ playbook_dir }}/files/eth0.nmconnection"
    dest: /etc/NetworkManager/system-connections/eth0.nmconnection
    owner: root
    group: root
    mode: '0600'
  register: nm_config_file

- name: network-manager - Restart NetworkManager
  include_tasks: "{{ playbook_dir }}/tasks/utils/restart_service.yaml"
  vars:
    target_service: NetworkManager

- name: network-manager - Force NetworkManager to learn new config
  ansible.builtin.shell: |
    cmd: |
      nmcli connection reload
      nmcli connection up eth0
      nmcli connection up Fortress-AP
  when: nm_config_file.changed
