- name: pihole - get rid of DNSMasq
  ansible.builtin.package:
    name:
      - dnsmasq
    state: absent

- name: pihole - Create group
  ansible.builtin.group:
    name: pihole
    state: present

- name: pihole - Create user
  ansible.builtin.user:
    name: pihole
    home: "/opt/pihole"
    shell: "/usr/sbin/nologin"
    comment: "PiHole"
    group: pihole
    password: "*"
    state: present
    remove: true
    force: true

- name: pihole - Ensure config directory exists
  ansible.builtin.file:
    state: directory
    path: /etc/pihole
    owner: pihole
    group: pihole
    mode: "0775"

- name: pihole - Deploy config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/files/pihole.toml.j2"
    dest: /etc/pihole/pihole.toml
    owner: pihole
    group: pihole
    mode: '0644'

- name: pihole - Run installer
  ansible.builtin.shell: |
    curl -sSL https://install.pi-hole.net | bash /dev/stdin --unattended
  environment:
    PIHOLE_SKIP_OS_CHECK: "true"
    PIHOLE_SELINUX: "true"
  args:
    creates: /etc/systemd/system/pihole-FTL.service
  register: pihole_install_result

- name: pihole - Set Admin Password
  ansible.builtin.shell: |
    pihole setpassword {{ gen_pihole_pw }}

- name: pihole - Install SQLite3
  ansible.builtin.package:
    name: "{{ 'sqlite' if ansible_os_family == 'RedHat' else 'sqlite3' }}"
    state: present

- name: pihole - Add blocklists
  ansible.builtin.shell: |
    sqlite3 /etc/pihole/gravity.db "INSERT OR IGNORE INTO adlist (address, enabled, comment) VALUES ('{{ item.url }}', 1, '{{ item.comment }}');"
  loop:
    - { url: 'https://raw.githubusercontent.com/nextdns/piracy-blocklists/master/torrent-clients', comment: '' }
    - { url: 'https://raw.githubusercontent.com/nextdns/piracy-blocklists/master/torrent-trackers', comment: '' }
    - { url: 'https://raw.githubusercontent.com/nextdns/piracy-blocklists/master/torrent-websites', comment: '' } 
    - { url: 'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt', comment: '' } 
    - { url: 'https://big.oisd.nl', comment: '' } 
    - { url: 'https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt', comment: '' }
  loop_control:
    pause: 5
  register: adlist_added

- name: pihole -  Update Gravity (Rebuild blocklist database)
  ansible.builtin.command: pihole -g
  when: adlist_added.changed

- name: pihole - Intercept Port 53 (DNS Redirect)
  ansible.posix.firewalld:
    zone: "{{ item.0 }}"
    permanent: true
    immediate: true
    state: enabled
    # Force a list of one dictionary per iteration
    port_forward:
      - port: 53
        proto: "{{ item.1 }}"
        toport: 53
        toaddr: 10.42.0.1
  with_nested:
    - ['nm-shared']
    - ['udp', 'tcp']

- name: pihole - Check if resolv.conf is already locked
  ansible.builtin.shell: |
    lsattr /etc/resolv.conf
  register: resolv_attr
  changed_when: false
  failed_when: false

- name: pihole - Reclaim and Lock DNS
  when: "'i' not in resolv_attr.stdout"
  ansible.builtin.shell: |
    rm -f /etc/resolv.conf
    echo "nameserver 127.0.0.1" > /etc/resolv.conf
    echo "options edns0 trust-ad" >> /etc/resolv.conf
    chattr +i /etc/resolv.conf
