- name: systemd-resolved - Install
  ansible.builtin.apt:
    name: systemd-resolved
    state: present

- name: systemd-resolved - Ensure config directory exists
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/resolved.conf.d
    owner: root
    group: root
    mode: "0755"

- name: systemd-resolved - Neutralise stub listener
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/fortress-no-stub.conf
    content: |
      [Resolve]
      DNSStubListener=no
    owner: root
    group: root
    mode: '0644'

- name: systemd-resolved - Restart
  include_tasks: "{{ playbook_dir }}/tasks/utils/restart_service.yaml"
  vars:
    target_service: systemd-resolved
