- name: tailscale-debian - Create keyring directory
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: tailscale-debian - Add GPG key
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg"
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: '0644'

- name: tailscale-debian - Add Repository
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: https://pkgs.tailscale.com/stable/debian
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: present

- name: tailscale-debian - Install
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true

- name: tailscale-debian - Ensure service is enabled
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: true

- name: tailscale-debian - Configure FirewallD for Tailscale
  ansible.posix.firewalld:
    interface: tailscale0
    zone: work
    state: enabled
    permanent: true

- name: tailscale-debian - Open port for inter-host communication
  ansible.posix.firewalld:
    zone: nm-shared
    permanent: true
    immediate: true
    state: enabled
    port: 41641/udp

